### ISSUE TITLE
log structure is unmaintainable

### ISSUE THREAD

**Issue by calston** [praekelt/jmbo-skeleton#7]
Currently log files get placed in an unwieldy directory structure 

/var/foo/log/bar/live/web/site/django.log

This is really difficult to maintain, rebuild after a failure, and do log rotation. Log files should rather go into 

/var/foo/log/bar-live-web-site.log
and
/var/foo/log/bar-live-web-site.err

That way it's easier to do things like multitail *.log in one place.

**Comment by hedleyroos** [comment]
It does not use nested paths anymore.
